# your-repo-name/.github/workflows/first_workflow.yml

name: First Workflow

on: push

jobs:
  first-job:
    name: Name of first step
    runs-on: ubuntu-latest
    steps:
      #step 1
      - name: Print a greeting
        run: echo Hi from our first workflow!

      #step 2 signature of the action we want to use from the GitHub marketplace
      - uses: actions/checkout@v2.3.4

  second-job:
    strategy:
      matrix:
        runtimes: [10, 12, 14]
        os_version: [ubuntu-latest, windows-latest]
    # a job will run for each possible combination of the variables
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}